trigger:
  - main
  - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  ImageName: 'deposit-api'
  phpVersion: 7.3
  ${{ if eq( variables['Build.SourceBranchName'], 'main' ) }}:
    buildVersion: 'latest'
  ${{ if eq( variables['Build.SourceBranchName'], 'develop' ) }}:
    buildVersion: 'test'

stages:
  - stage: Test
    displayName: Run Laravel Tests'
    jobs:
      - job: Test
        displayName: Run Laravel Tests
        steps:
          - script: |
              sudo update-alternatives --set php /usr/bin/php$(phpVersion)
              sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
              sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
              sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
              sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
              php -version
              cd src
              composer install --no-interaction
              touch .env
              php artisan key:generate
              php artisan migrate --seed
              php artisan test
            displayName: 'Run Laravel Tests'
            workingDirectory: $(Build.SourcesDirectory)
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build and push Docker image
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'Docker hub aranxa'
              repository: 'codinaaranxa/deposit-api'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: $(buildVersion)