trigger:
  - main
  - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  ImageName: 'deposit-api'
  ${{ if eq( variables['Build.SourceBranchName'], 'main' ) }}:
    buildVersion: 'latest'
  ${{ if eq( variables['Build.SourceBranchName'], 'develop' ) }}:
    buildVersion: 'test'

stages:
  - stage: Test
    displayName: Run Laravel Tests
    jobs:
      - job: Test
        displayName: Run Laravel Tests
        steps:
          - script: |
              cd src
              composer install --no-interaction
              touch .env
              php artisan key:generate
              php artisan migrate --seed
              php artisan test
            displayName: 'Run Laravel Tests'
            workingDirectory: $(Build.SourcesDirectory)
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build and push Docker image
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'Docker hub aranxa'
              repository: 'codinaaranxa/deposit-api'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: $(buildVersion)