version: '3.7'
services:
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"

    app:
        build: .
        image: 'deposit'
        ports:
            - '5000:80'
        volumes:
            - ./src:/var/www/html
            - /var/www/html/vendor
        links:
            - mysql
        depends_on:
            - mysql
        env_file:
            -   src/.env.local

    mysql:
        image: mysql:5.7
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: 'deposit_db'
            MYSQL_ALLOW_EMPTY_PASSWORD: 0
            MYSQL_USER: 'username'
            MYSQL_PASSWORD: 'password'