version: '3.7'
services:
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"

    app:
        build: .
        image: 'deposit'
        ports:
            - '5000:80'
        volumes:
            - ./src:/var/www/html
            - /var/www/html/vendor
            - ./setup.sh:/var/www/setup.sh
        entrypoint: /var/www/setup.sh
        links:
            - mysql
        depends_on:
            - mysql
        environment:
            DB_HOST: 'mysql'
            DB_NAME: 'deposit_db'
            DB_PORT: 3306
            DB_USERNAME: 'username'
            DB_PASSWORD: 'password'
            APP_DEBUG: true
            APP_KEY: 'base64:Q0gqyvX+LwEFWOW3QYqHrMT3s6CbbDka6plbeK8o1KU='
            APP_ENV: 'local'

    mysql:
        image: mysql:5.7
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: 'deposit_db'
            MYSQL_ALLOW_EMPTY_PASSWORD: 0
            MYSQL_USER: 'username'
            MYSQL_PASSWORD: 'password'